package com.nordicpeak.flowengine.sharing.beans;

import java.lang.reflect.Field;
import java.util.List;

import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.OneToMany;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.reflection.ReflectionUtils;
import se.unlogic.standardutils.xml.GeneratedElementable;
import se.unlogic.standardutils.xml.XMLElement;

@Table(name = "flowsharing_repositories")
@XMLElement
public class Repository extends GeneratedElementable {

	public static final Field SOURCES_FIELD = ReflectionUtils.getField(Repository.class, "sources");

	@DAOManaged(autoGenerated = true)
	@Key
	private Integer repositoryID;

	@DAOManaged
	@OneToMany
	@XMLElement
	private List<Source> sources;

	public Integer getRepositoryID() {

		return repositoryID;
	}

	public void setRepositoryID(Integer sourceID) {

		this.repositoryID = sourceID;
	}

	@Override
	public String toString() {

		return "ID=" + repositoryID;
	}

	public List<Source> getSources() {

		return sources;
	}

	public void setSources(List<Source> sources) {

		this.sources = sources;
	}

}
