package com.nordicpeak.flowengine.persondatasavinginformer.beans;

import java.io.Serializable;

import com.nordicpeak.flowengine.persondatasavinginformer.enums.StorageType;
import com.nordicpeak.flowengine.persondatasavinginformer.query.PersonDataInformerQueryInstance;

import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.ManyToOne;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.xml.GeneratedElementable;
import se.unlogic.standardutils.xml.XMLElement;

@Table(name = "person_data_informer_query_instance_settings_storage")
@XMLElement(name = "StorageSetting")
public class PersonDataInformerQueryInstanceSettingStorage extends GeneratedElementable implements Serializable {

	private static final long serialVersionUID = -6359529375088235771L;

	@DAOManaged(autoGenerated = true)
	@Key
	@XMLElement
	private Integer settingStorageID;

	@DAOManaged(columnName = "queryInstanceID")
	@ManyToOne
	@XMLElement
	private PersonDataInformerQueryInstance queryInstance;

	@DAOManaged
	@XMLElement
	private Integer period;

	@DAOManaged(columnName = "type")
	@XMLElement
	private StorageType storageType;

	@DAOManaged
	@XMLElement
	private String description;

	public Integer getSettingStorageID() {

		return settingStorageID;
	}

	public void setSettingStorageID(Integer settingStorageID) {

		this.settingStorageID = settingStorageID;
	}

	public PersonDataInformerQueryInstance getQueryInstance() {

		return queryInstance;
	}

	public void setQueryInstance(PersonDataInformerQueryInstance queryInstance) {

		this.queryInstance = queryInstance;
	}

	public Integer getPeriod() {

		return period;
	}

	public void setPeriod(Integer period) {

		this.period = period;
	}

	public StorageType getStorageType() {

		return storageType;
	}

	public void setStorageType(StorageType storageType) {

		this.storageType = storageType;
	}

	public String getDescription() {

		return description;
	}

	public void setDescription(String description) {

		this.description = description;
	}

}
