package com.nordicpeak.flowengine.beans;

import java.io.Serializable;
import java.util.Collections;
import java.util.List;

import com.nordicpeak.flowengine.comparators.GroupNameComparator;
import com.nordicpeak.flowengine.utils.FlowFamilyUtils;

import se.unlogic.hierarchy.core.beans.Group;
import se.unlogic.hierarchy.core.beans.User;
import se.unlogic.hierarchy.core.utils.UserUtils;
import se.unlogic.hierarchy.foregroundmodules.usersessionadmin.UserNameComparator;
import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.ManyToOne;
import se.unlogic.standardutils.dao.annotations.OneToMany;
import se.unlogic.standardutils.dao.annotations.SimplifiedRelation;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.xml.GeneratedElementable;
import se.unlogic.standardutils.xml.XMLElement;

@Table(name = "flowengine_flow_family_automanager_rules")
@XMLElement
public class AutoManagerAssignmentRule extends GeneratedElementable implements Serializable {
	
	private static final long serialVersionUID = 2906850629442177083L;
	
	@DAOManaged(autoGenerated = true)
	@Key
	@XMLElement
	private Integer ruleID;
	
	@XMLElement
	private String generatedRuleID;
	
	@DAOManaged(columnName = "flowFamilyID")
	@ManyToOne
	private FlowFamily flowFamily;
	
	@DAOManaged
	@XMLElement
	private String attributeName;
	
	@DAOManaged
	@XMLElement
	private boolean invert;

	@DAOManaged
	@XMLElement
	private boolean includeUnsetAttribute;	
	
	@DAOManaged
	@OneToMany(autoGet = true, autoAdd = true, autoUpdate = true)
//	@SimplifiedRelation(table = "flowengine_flow_family_automanager_rule_values", remoteValueColumnName = "value")
	@XMLElement(fixCase = true)
	private List<AutoManagerAssignmentRuleAttributeValue> values;
	
	@DAOManaged
	@OneToMany(autoGet = true, autoAdd = true, autoUpdate = true)
	@SimplifiedRelation(table = "flowengine_flow_family_automanager_rule_users", remoteValueColumnName = "userID")
	@XMLElement(fixCase = true)
	private List<Integer> userIDs;
	
	@DAOManaged
	@OneToMany(autoGet = true, autoAdd = true, autoUpdate = true)
	@SimplifiedRelation(table = "flowengine_flow_family_automanager_rule_groups", remoteValueColumnName = "groupID")
	@XMLElement(fixCase = true)
	private List<Integer> groupIDs;
	
	@XMLElement(fixCase = true)
	private List<User> users;
	
	@XMLElement(fixCase = true)
	private List<Group> groups;
	
	public Integer getRuleID() {
		return ruleID;
	}
	
	public void setRuleID(Integer ruleID) {
		this.ruleID = ruleID;
	}
	
	public void setGeneratedRuleID(String generatedRuleID) {
		this.generatedRuleID = generatedRuleID;
	}
	
	public boolean isInverted() {
		return invert;
	}
	
	public void setInverted(boolean inverted) {
		this.invert = inverted;
	}

	public boolean isIncludeUnsetAttribute() {
		return includeUnsetAttribute;
	}

	public void setIncludeUnsetAttribute(boolean includeUnsetAttribute) {
		this.includeUnsetAttribute = includeUnsetAttribute;
	}
	
	public FlowFamily getFlowFamily() {
		return flowFamily;
	}
	
	public void setFlowFamily(FlowFamily flowFamily) {
		this.flowFamily = flowFamily;
	}
	
	public List<Integer> getUserIDs() {
		return userIDs;
	}
	
	public void setUserIDs(List<Integer> userIDs) {
		this.userIDs = userIDs;
		users = null;
	}
	
	public List<Integer> getGroupIDs() {
		return groupIDs;
	}
	
	public void setGroupIDs(List<Integer> groupIDs) {
		this.groupIDs = groupIDs;
		groups = null;
	}
	
	public String getAttributeName() {
		return attributeName;
	}
	
	public void setAttributeName(String attributeName) {
		this.attributeName = attributeName;
	}
	
	
	public List<AutoManagerAssignmentRuleAttributeValue> getValues() {
		return values;
	}

	public void setValues(List<AutoManagerAssignmentRuleAttributeValue> values) {
		this.values = values;
	}

	public void setUsers(List<User> users) {
		
		this.users = users;
		
		if (users == null) {
			
			userIDs = null;
			
		} else {
			
			userIDs = UserUtils.getUserIDs(users);
		}
	}
	
	public void setGroups(List<Group> groups) {
		
		this.groups = groups;
		
		if (groups == null) {
			
			groupIDs = null;
			
		} else {
			
			groupIDs = UserUtils.getGroupIDs(groups);
		}
	}
	
	public void setUsersAndGroups(List<User> allowedManagers, List<Group> allowedManagerGroups, boolean removeMissingIDs) {
		
		if (userIDs != null && users == null) {
			
			users = FlowFamilyUtils.filterSelectedManagerUsers(allowedManagers, userIDs, null);
			
			if (users != null) {
				Collections.sort(users, UserNameComparator.getInstance());
			}
			
			if (removeMissingIDs) {
				
				userIDs = UserUtils.getUserIDs(users);
			}
		}
		
		if (groupIDs != null && groups == null) {
			
			groups = FlowFamilyUtils.filterSelectedManagerGroups(allowedManagerGroups, groupIDs, null);
			
			if (groups != null) {
				Collections.sort(groups, GroupNameComparator.getInstance());
			}
			
			if (removeMissingIDs) {
				
				groupIDs = UserUtils.getGroupIDs(groups);
			}
		}
	}
	
}
