package com.nordicpeak.flowengine.beans;

import java.lang.reflect.Field;
import java.sql.Timestamp;

import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.reflection.ReflectionUtils;

@Table(name = "flowengine_aborted_flow_instances")
public class AbortedFlowInstance {

	public static final Field ID_FIELD = ReflectionUtils.getField(AbortedFlowInstance.class, "abortID");
	public static final Field FLOW_INSTANCE_ID_FIELD = ReflectionUtils.getField(AbortedFlowInstance.class, "flowInstanceID");
	
	@DAOManaged(autoGenerated = true)
	@Key
	private Integer abortID;

	@DAOManaged
	private Integer flowInstanceID;
	
	@DAOManaged
	private Integer flowFamilyID;

	@DAOManaged
	private Integer flowID;

	@DAOManaged
	private Integer stepID;

	@DAOManaged
	private Timestamp added;

	public Integer getAbortID() {

		return abortID;
	}

	public void setAbortID(Integer abortID) {

		this.abortID = abortID;
	}

	/**
	 * Only set when user removes their saved but unsubmitted flow instances
	 */
	public Integer getFlowInstanceID() {
		return flowInstanceID;
	}

	public void setFlowInstanceID(Integer flowInstanceID) {
		this.flowInstanceID = flowInstanceID;
	}

	public Integer getFlowFamilyID() {

		return flowFamilyID;
	}

	public void setFlowFamilyID(Integer flowFamilyID) {

		this.flowFamilyID = flowFamilyID;
	}

	public Integer getFlowID() {

		return flowID;
	}

	public void setFlowID(Integer flowID) {

		this.flowID = flowID;
	}

	public Integer getStepID() {

		return stepID;
	}

	public void setStepID(Integer stepID) {

		this.stepID = stepID;
	}

	public Timestamp getAdded() {

		return added;
	}

	public void setAdded(Timestamp added) {

		this.added = added;
	}
}
