package com.nordicpeak.flowengine.beans;

import java.io.Serializable;
import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.ManyToOne;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.xml.GeneratedElementable;
import se.unlogic.standardutils.xml.XMLElement;

@Table(name = "flowengine_flow_family_automanager_rule_values")
@XMLElement
public class AutoManagerAssignmentRuleAttributeValue extends GeneratedElementable implements Serializable {
	
	public AutoManagerAssignmentRuleAttributeValue(AutoManagerAssignmentRule rule, String value) {
		this.autoManagerAssignmentRule = rule;
		this.value = value;
	}

	
	public AutoManagerAssignmentRuleAttributeValue() {
	}


	private static final long serialVersionUID = -58633882754227186L;

	@DAOManaged(autoGenerated = true)
	@Key
	@XMLElement
	private Integer valueID;
	
	@DAOManaged(columnName = "ruleID")
	@ManyToOne
	@XMLElement
	private AutoManagerAssignmentRule autoManagerAssignmentRule;
	
	@DAOManaged
	@XMLElement(fixCase = true)
	private String value;

	public Integer getValueID() {
		return valueID;
	}

	public void setValueID(Integer valueID) {
		this.valueID = valueID;
	}

	public AutoManagerAssignmentRule getAutoManagerAssignmentRule() {
		return autoManagerAssignmentRule;
	}

	public void setAutoManagerAssignmentRule(AutoManagerAssignmentRule autoManagerAssignmentRule) {
		this.autoManagerAssignmentRule = autoManagerAssignmentRule;
	}

	public String getValue() {
		return value;
	}

	public void setValue(String value) {
		this.value = value;
	}


	@Override
	public String toString() {
		return "AutoManagerAssignmentRuleAttributeValue [valueID=" + valueID + ", autoManagerAssignmentRule=" + autoManagerAssignmentRule + ", value=" + value + ", getValue()=" + getValue() + "]";
	}
	
	
	
}
