package com.nordicpeak.flowengine.beans;

import java.lang.reflect.Field;
import java.sql.Timestamp;

import se.unlogic.hierarchy.core.beans.User;
import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.ManyToOne;
import se.unlogic.standardutils.dao.annotations.OrderBy;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.enums.Order;
import se.unlogic.standardutils.reflection.ReflectionUtils;
import se.unlogic.standardutils.xml.GeneratedElementable;
import se.unlogic.standardutils.xml.XMLElement;

@Table(name = "flowengine_flow_family_events")
@XMLElement
public class FlowFamilyEvent extends GeneratedElementable {

	public static final Field FLOW_FAMILY_RELATION = ReflectionUtils.getField(FlowFamilyEvent.class, "flowFamily");

	@DAOManaged(autoGenerated = true)
	@Key
	@XMLElement
	private Integer eventID;

	@DAOManaged(columnName = "flowFamilyID")
	@ManyToOne
	@XMLElement
	private FlowFamily flowFamily;

	@DAOManaged
	@XMLElement
	private Integer flowVersion;

	@DAOManaged
	@OrderBy(order = Order.DESC)
	@XMLElement
	protected Timestamp added;

	@DAOManaged(dontUpdateIfNull = true)
	@XMLElement(name = "poster")
	protected User poster;

	@DAOManaged
	@XMLElement
	protected String message;

	public FlowFamilyEvent() {};

	public FlowFamilyEvent(FlowFamily flowFamily, Integer flowVersion, Timestamp added, User poster, String message) {
		super();

		if (flowFamily == null) {
			throw new NullPointerException("flowFamily can not be null");
		}

		this.flowFamily = flowFamily;
		this.flowVersion = flowVersion;
		this.added = added;
		this.poster = poster;
		this.message = message;
	}

	public Integer getEventID() {

		return eventID;
	}

	public void setEventID(Integer eventID) {

		this.eventID = eventID;
	}

	public FlowFamily getFlowFamily() {

		return flowFamily;
	}

	public void setFlowFamily(FlowFamily flowFamily) {

		this.flowFamily = flowFamily;
	}

	public Integer getFlowVersion() {

		return flowVersion;
	}

	public void setFlowVersion(Integer flowVersion) {

		this.flowVersion = flowVersion;
	}

	public Timestamp getAdded() {

		return added;
	}

	public void setAdded(Timestamp added) {

		this.added = added;
	}

	public User getPoster() {

		return poster;
	}

	public void setPoster(User poster) {

		this.poster = poster;
	}

	public String getMessage() {

		return message;
	}

	public void setMessage(String message) {

		this.message = message;
	}

	@Override
	public String toString() {

		return "FlowFamilyEvent (ID: " + eventID + ", poster: " + poster + ")";
	}

}
