package com.nordicpeak.flowengine.queries.generalmapquery.configuration;

import java.io.Serializable;
import java.util.List;

import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.ManyToOne;
import se.unlogic.standardutils.dao.annotations.OneToMany;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.xml.GeneratedElementable;
import se.unlogic.standardutils.xml.XMLElement;

@Table(name = "general_map_query_printservice_outputformats")
@XMLElement
public class OutputFormat extends GeneratedElementable implements Serializable {

	private static final long serialVersionUID = -7389335709465343324L;

	@Key
	@DAOManaged(autoGenerated = true)
	@XMLElement
	private Integer outputFormatID;

	@DAOManaged
	@XMLElement
	private String name;

	@DAOManaged
	@XMLElement
	private String format;

	@DAOManaged(columnName = "printServiceID")
	@ManyToOne
	@XMLElement
	private PrintService printService;

	@DAOManaged
	@OneToMany
	@XMLElement
	private List<MapPrint> mapPrints;
	
	public Integer getOutputFormatID() {

		return outputFormatID;
	}

	public void setOutputFormatID(Integer outputFormatID) {

		this.outputFormatID = outputFormatID;
	}

	public String getName() {

		return name;
	}

	public void setName(String name) {

		this.name = name;
	}

	public String getFormat() {

		return format;
	}

	public void setFormat(String format) {

		this.format = format;
	}

	public PrintService getPrintService() {

		return printService;
	}

	public void setPrintService(PrintService printService) {

		this.printService = printService;
	}

}
