package com.nordicpeak.flowengine.queries.generalmapquery.configuration;

import java.io.Serializable;
import java.util.List;

import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.ManyToOne;
import se.unlogic.standardutils.dao.annotations.OneToMany;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.xml.GeneratedElementable;
import se.unlogic.standardutils.xml.XMLElement;

@Table(name = "general_map_query_printservice_scales")
@XMLElement
public class Scale extends GeneratedElementable implements Serializable {

	private static final long serialVersionUID = 4733204395328247518L;

	@Key
	@DAOManaged(autoGenerated = true)
	@XMLElement
	private Integer scaleID;

	@DAOManaged
	@XMLElement
	private String name;

	@DAOManaged
	@XMLElement
	private Integer scale;

	@DAOManaged(columnName = "printServiceID")
	@ManyToOne
	@XMLElement
	private PrintService printService;

	@DAOManaged
	@OneToMany
	@XMLElement
	private List<MapPrint> mapPrints;
	
	public Integer getScaleID() {

		return scaleID;
	}

	public void setScaleID(Integer scaleID) {

		this.scaleID = scaleID;
	}

	public String getName() {

		return name;
	}

	public void setName(String name) {

		this.name = name;
	}

	public Integer getScale() {

		return scale;
	}

	public void setScale(Integer scale) {

		this.scale = scale;
	}

	public PrintService getPrintService() {

		return printService;
	}

	public void setPrintService(PrintService printService) {

		this.printService = printService;
	}

}
