
package com.nordicpeak.flowengine.integration.callback;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IntegrationCallbackService", targetNamespace = "http://www.oeplatform.org/version/1.0/schemas/integration/callback", wsdlLocation = "file:/C:/Users/Unlogic/Workspace/FlowEngineIntegrationCallback/src/com/nordicpeak/flowengine/integration/callback/IntegrationCallbackService.wsdl")
public class IntegrationCallbackService
    extends Service
{

    private final static URL INTEGRATIONCALLBACKSERVICE_WSDL_LOCATION;
    private final static WebServiceException INTEGRATIONCALLBACKSERVICE_EXCEPTION;
    private final static QName INTEGRATIONCALLBACKSERVICE_QNAME = new QName("http://www.oeplatform.org/version/1.0/schemas/integration/callback", "IntegrationCallbackService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Unlogic/Workspace/FlowEngineIntegrationCallback/src/com/nordicpeak/flowengine/integration/callback/IntegrationCallbackService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INTEGRATIONCALLBACKSERVICE_WSDL_LOCATION = url;
        INTEGRATIONCALLBACKSERVICE_EXCEPTION = e;
    }

    public IntegrationCallbackService() {
        super(__getWsdlLocation(), INTEGRATIONCALLBACKSERVICE_QNAME);
    }

    public IntegrationCallbackService(WebServiceFeature... features) {
        super(__getWsdlLocation(), INTEGRATIONCALLBACKSERVICE_QNAME, features);
    }

    public IntegrationCallbackService(URL wsdlLocation) {
        super(wsdlLocation, INTEGRATIONCALLBACKSERVICE_QNAME);
    }

    public IntegrationCallbackService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INTEGRATIONCALLBACKSERVICE_QNAME, features);
    }

    public IntegrationCallbackService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IntegrationCallbackService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IntegrationCallback
     */
    @WebEndpoint(name = "IntegrationCallback")
    public IntegrationCallback getIntegrationCallback() {
        return super.getPort(new QName("http://www.oeplatform.org/version/1.0/schemas/integration/callback", "IntegrationCallback"), IntegrationCallback.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IntegrationCallback
     */
    @WebEndpoint(name = "IntegrationCallback")
    public IntegrationCallback getIntegrationCallback(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.oeplatform.org/version/1.0/schemas/integration/callback", "IntegrationCallback"), IntegrationCallback.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INTEGRATIONCALLBACKSERVICE_EXCEPTION!= null) {
            throw INTEGRATIONCALLBACKSERVICE_EXCEPTION;
        }
        return INTEGRATIONCALLBACKSERVICE_WSDL_LOCATION;
    }

}
