package com.nordicpeak.flowengine.queries.generalmapquery.configuration;

import java.io.Serializable;
import java.util.List;

import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.ManyToOne;
import se.unlogic.standardutils.dao.annotations.OneToMany;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.xml.GeneratedElementable;
import se.unlogic.standardutils.xml.XMLElement;

@Table(name = "general_map_query_printservice_resolutions")
@XMLElement
public class Resolution extends GeneratedElementable implements Serializable {

	private static final long serialVersionUID = 2398910825166080064L;

	@Key
	@DAOManaged(autoGenerated = true)
	@XMLElement
	private Integer resolutionID;

	@DAOManaged
	@XMLElement
	private String name;

	@DAOManaged
	@XMLElement
	private Integer resolution;

	@DAOManaged(columnName="printServiceID")
	@ManyToOne
	@XMLElement
	private PrintService printService;
	
	@DAOManaged
	@OneToMany
	@XMLElement
	private List<MapPrint> mapPrints;
	
	public Integer getResolutionID() {

		return resolutionID;
	}

	public void setResolutionID(Integer resolutionID) {

		this.resolutionID = resolutionID;
	}

	public String getName() {

		return name;
	}

	public void setName(String name) {

		this.name = name;
	}

	public Integer getResolution() {

		return resolution;
	}

	public void setResolution(Integer resolution) {

		this.resolution = resolution;
	}

}
