
package se.teis.proxy;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BixEnvelope", targetNamespace = "http://tieto.com/bix/", wsdlLocation = "/se/teis/wsdl/teis.wsdl")
public class BixEnvelope
    extends Service
{

    private final static URL BIXENVELOPE_WSDL_LOCATION = BixEnvelope.class.getResource("/se/teis/wsdl/teis.wsdl");
    private final static QName BIXENVELOPE_QNAME = new QName("http://tieto.com/bix/", "BixEnvelope");

    public BixEnvelope() {
        super(__getWsdlLocation(), BIXENVELOPE_QNAME);
    }

    public BixEnvelope(WebServiceFeature... features) {
        super(__getWsdlLocation(), BIXENVELOPE_QNAME, features);
    }

    public BixEnvelope(URL wsdlLocation) {
        super(wsdlLocation, BIXENVELOPE_QNAME);
    }

    public BixEnvelope(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BIXENVELOPE_QNAME, features);
    }

    public BixEnvelope(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BixEnvelope(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IBixEnvelope
     */
    @WebEndpoint(name = "BasicHttpBinding_IBixEnvelope")
    public IBixEnvelope getBasicHttpBindingIBixEnvelope() {
        return super.getPort(new QName("http://tieto.com/bix/", "BasicHttpBinding_IBixEnvelope"), IBixEnvelope.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IBixEnvelope
     */
    @WebEndpoint(name = "BasicHttpBinding_IBixEnvelope")
    public IBixEnvelope getBasicHttpBindingIBixEnvelope(WebServiceFeature... features) {
        return super.getPort(new QName("http://tieto.com/bix/", "BasicHttpBinding_IBixEnvelope"), IBixEnvelope.class, features);
    }

    private static URL __getWsdlLocation() {

    	return BIXENVELOPE_WSDL_LOCATION;
    }

}
