package com.nordicpeak.flowengine.enums;

public enum EventType {
	UPDATED,
	SIGNED,
	SIGNING_SKIPPED,
	PAYED,
	SUBMITTED,
	STATUS_UPDATED,
	MANAGERS_UPDATED,
	OWNERS_UPDATED,
	CUSTOMER_NOTIFICATION_SENT,
	CUSTOMER_MESSAGE_SENT,
	MANAGER_MESSAGE_SENT,
	CUSTOMERS_READ_MESSAGE,
	OTHER_EVENT
}
