package com.nordicpeak.flowengine.queries.generalmapquery;

import java.io.Serializable;
import java.sql.Blob;
import java.sql.SQLException;

import javax.sql.rowset.serial.SerialBlob;
import javax.sql.rowset.serial.SerialException;

import com.nordicpeak.flowengine.queries.generalmapquery.configuration.MapPrint;

import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.ManyToOne;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.xml.GeneratedElementable;
import se.unlogic.standardutils.xml.XMLElement;

@Table(name = "general_map_query_instance_prints")
@XMLElement
public class GeneralMapQueryInstancePrint extends GeneratedElementable implements Serializable {

	private static final long serialVersionUID = -8980174708468159021L;

	@Key
	@DAOManaged(autoGenerated = true)
	@XMLElement
	private Integer queryPrintID;

	@DAOManaged(columnName = "queryInstanceID")
	@ManyToOne
	private GeneralMapQueryInstance generalMapQueryInstance;

	@DAOManaged
	@XMLElement
	private String layout;

	@DAOManaged
	@XMLElement
	private String format;

	@DAOManaged
	@XMLElement
	private Integer scale;

	@DAOManaged
	@XMLElement
	private Integer resolution;

	@DAOManaged
	@XMLElement
	private boolean useInPreview;

	@DAOManaged
	private Blob mapImage;

	public GeneralMapQueryInstancePrint() {

	}

	public GeneralMapQueryInstancePrint(GeneralMapQueryPrint generalMapQueryPrint, Blob mapImage) {

		MapPrint mapPrint = generalMapQueryPrint.getMapPrint();

		this.layout = mapPrint.getLayout().getName();
		this.format = mapPrint.getOutputFormat().getFormat();
		this.scale = generalMapQueryPrint.getScale();
		this.resolution = mapPrint.getResolution().getResolution();
		this.useInPreview = generalMapQueryPrint.isUseInPreview();
		this.mapImage = mapImage;
	}

	public Integer getQueryPrintID() {

		return queryPrintID;
	}

	public void setQueryPrintID(Integer queryPrintID) {

		this.queryPrintID = queryPrintID;
	}

	public GeneralMapQueryInstance getGeneralMapQueryInstance() {

		return generalMapQueryInstance;
	}

	public void setGeneralMapQueryInstance(GeneralMapQueryInstance generalMapQueryInstance) {

		this.generalMapQueryInstance = generalMapQueryInstance;
	}

	public String getLayout() {

		return layout;
	}

	public void setLayout(String layout) {

		this.layout = layout;
	}

	public String getFormat() {

		return format;
	}

	public void setFormat(String format) {

		this.format = format;
	}

	public Integer getScale() {

		return scale;
	}

	public void setScale(Integer scale) {

		this.scale = scale;
	}

	public Integer getResolution() {

		return resolution;
	}

	public void setResolution(Integer resolution) {

		this.resolution = resolution;
	}

	public boolean isUseInPreview() {

		return useInPreview;
	}

	public void setUseInPreview(boolean useInPreview) {

		this.useInPreview = useInPreview;
	}

	public Blob getMapImage() {

		return mapImage;
	}

	public void setMapImage(Blob mapImage) {

		this.mapImage = mapImage;
	}

	protected final Object writeReplace() {

		try {

			if (mapImage != null) {
				mapImage = new SerialBlob(mapImage);
			}

		} catch (SerialException e) {

		} catch (SQLException e) {

		}

		return this;

	}

}
