package com.nordicpeak.teis.enums;


public enum LogEventType {

	FLOW_INSTANCE_SEND_SUCCESS,
	FLOW_INSTANCE_DELIERY_CONFIRMED,
	FLOW_INSTANCE_SEND_FAILED,
	FLOW_INSTANCE_NOT_FOUND,
	MESSAGE_SEND_SUCCESS,
	MESSAGE_SEND_FAILED,
	MESSAGE_NOT_FOUND
}
