package com.nordicpeak.flowengine.flowapprovalmodule.beans;

import java.sql.Timestamp;

import se.unlogic.hierarchy.core.beans.User;
import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.ManyToOne;
import se.unlogic.standardutils.dao.annotations.OrderBy;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.enums.Order;
import se.unlogic.standardutils.xml.GeneratedElementable;
import se.unlogic.standardutils.xml.XMLElement;

@Table(name = "flowapproval_reminders")
@XMLElement(name = "Reminder")
public class FlowApprovalReminder extends GeneratedElementable {
	
	@Key
	@DAOManaged(autoGenerated = true)
	@XMLElement
	private Integer reminderID;

	@DAOManaged(columnName = "activityProgressID")
	@ManyToOne
	@XMLElement
	private FlowApprovalActivityProgress activityProgress;
	
	@DAOManaged
	@OrderBy(order = Order.DESC)
	@XMLElement
	private Timestamp added;
	
	@DAOManaged
	@XMLElement
	private ReminderType reminderType;
	
	@DAOManaged(columnName = "userID")
	@XMLElement
	private User user;

	public FlowApprovalReminder() {}
	
	public FlowApprovalReminder(FlowApprovalActivityProgress activityProgress, Timestamp currentTimestamp, ReminderType reminderType, User user) {

		this.activityProgress = activityProgress;
		this.added = currentTimestamp;
		this.reminderType = reminderType;
		this.user = user;
	}

	public Integer getReminderID() {
		return reminderID;
	}

	public void setReminderID(Integer reminderID) {
		this.reminderID = reminderID;
	}

	public FlowApprovalActivityProgress getActivityProgress() {
		return activityProgress;
	}

	public void setActivityProgress(FlowApprovalActivityProgress activityProgress) {
		this.activityProgress = activityProgress;
	}

	public Timestamp getAdded() {
		return added;
	}

	public void setAdded(Timestamp added) {
		this.added = added;
	}

	public ReminderType getReminderType() {
		return reminderType;
	}

	public void setReminderType(ReminderType reminderType) {
		this.reminderType = reminderType;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}
}
