package com.nordicpeak.flowengine.flowapprovalmodule.beans;

import java.lang.reflect.Field;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

import se.unlogic.hierarchy.core.beans.User;
import se.unlogic.hierarchy.core.interfaces.AccessInterface;
import se.unlogic.hierarchy.core.utils.UserUtils;
import se.unlogic.standardutils.collections.CollectionUtils;
import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.ManyToOne;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.reflection.ReflectionUtils;
import se.unlogic.standardutils.xml.GeneratedElementable;
import se.unlogic.standardutils.xml.XMLElement;

@Table(name = "flowapproval_activity_progress")
@XMLElement(name = "ActivityProgress")
public class FlowApprovalActivityProgress extends GeneratedElementable implements AccessInterface {

	public static final Field ACTIVITY_RELATION = ReflectionUtils.getField(FlowApprovalActivityProgress.class, "activity");

	@Key
	@DAOManaged(autoGenerated = true)
	@XMLElement
	private Integer activityProgressID;

	@DAOManaged(columnName = "activityID")
	@ManyToOne
	@XMLElement
	private FlowApprovalActivity activity;

	@DAOManaged
	@XMLElement
	private Integer flowInstanceID;

	@DAOManaged
	@XMLElement
	private Timestamp added;

	@DAOManaged
	@XMLElement
	private Timestamp completed;

	@DAOManaged
	@XMLElement
	private boolean denied;

	@DAOManaged(columnName = "completingUserID")
	@XMLElement(name = "CompletingUser")
	private User completingUser;

	@DAOManaged(columnName = "responsibleAttributedUserID")
	@XMLElement(name = "ResponsibleAttributedUser")
	private User responsibleAttributedUser;

	@DAOManaged
	@XMLElement
	private String comment;
	
	@DAOManaged
	@XMLElement
	private boolean automaticReminderSent;

	public Integer getActivityProgressID() {
		return activityProgressID;
	}

	public void setActivityProgressID(Integer activityProgressID) {
		this.activityProgressID = activityProgressID;
	}

	public FlowApprovalActivity getActivity() {
		return activity;
	}

	public void setActivity(FlowApprovalActivity activity) {
		this.activity = activity;
	}

	public Integer getFlowInstanceID() {
		return flowInstanceID;
	}

	public void setFlowInstanceID(Integer flowInstanceID) {
		this.flowInstanceID = flowInstanceID;
	}

	public Timestamp getAdded() {
		return added;
	}

	public void setAdded(Timestamp added) {
		this.added = added;
	}

	public Timestamp getCompleted() {
		return completed;
	}

	public void setCompleted(Timestamp completed) {
		this.completed = completed;
	}

	public boolean isDenied() {
		return denied;
	}

	public void setDenied(boolean denied) {
		this.denied = denied;
	}

	public User getCompletingUser() {
		return completingUser;
	}

	public void setCompletingUser(User completer) {
		this.completingUser = completer;
	}

	public String getComment() {
		return comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public User getResponsibleAttributedUser() {
		return responsibleAttributedUser;
	}

	public void setResponsibleAttributedUser(User responsibleAttributedUser) {
		this.responsibleAttributedUser = responsibleAttributedUser;
	}

	public boolean isAutomaticReminderSent() {
		return automaticReminderSent;
	}

	public void setAutomaticReminderSent(boolean automaticReminderSent) {
		this.automaticReminderSent = automaticReminderSent;
	}

	@Override
	public String toString() {
		return getClass().getSimpleName() + " (activityProgressID=" + activityProgressID + ", activity=" + (activity == null ? null : activity.getActivityID()) + ", flowInstanceID=" + flowInstanceID + ", added=" + added + ", completed=" + completed + ", denied=" + denied + ", completingUser=" + completingUser + ")";
	}

	@Override
	public boolean allowsAdminAccess() {
		return false;
	}

	@Override
	public boolean allowsUserAccess() {
		return false;
	}

	@Override
	public boolean allowsAnonymousAccess() {
		return false;
	}

	@Override
	public Collection<Integer> getAllowedGroupIDs() {
		return UserUtils.getGroupIDs(activity.getResponsibleGroups());
	}

	@Override
	public Collection<Integer> getAllowedUserIDs() {

		if (CollectionUtils.isEmpty(activity.getResponsibleUsers()) && responsibleAttributedUser == null) {
			return null;
		}

		List<Integer> userIDs = new ArrayList<Integer>(CollectionUtils.getSize(activity.getResponsibleUsers()) + 1);

		if (activity.getResponsibleUsers() != null) {
			for (FlowApprovalActivityResponsibleUser responsibleUser : activity.getResponsibleUsers()) {

				if (!responsibleUser.isFallback() || (activity.getResponsibleUserAttributeName() != null && responsibleAttributedUser == null)) {
					userIDs.add(responsibleUser.getUser().getUserID());
				}
			}
		}

		if (responsibleAttributedUser != null) {
			userIDs.add(responsibleAttributedUser.getUserID());
		}

		return userIDs;
	}
}
