package com.nordicpeak.flowengine.flowapprovalmodule.beans;

import java.lang.reflect.Field;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

import se.unlogic.hierarchy.core.beans.User;
import se.unlogic.hierarchy.core.interfaces.AccessInterface;
import se.unlogic.hierarchy.core.utils.UserUtils;
import se.unlogic.standardutils.collections.CollectionUtils;
import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.ManyToOne;
import se.unlogic.standardutils.dao.annotations.OneToMany;
import se.unlogic.standardutils.dao.annotations.SimplifiedRelation;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.reflection.ReflectionUtils;
import se.unlogic.standardutils.xml.GeneratedElementable;
import se.unlogic.standardutils.xml.XMLElement;

@Table(name = "flowapproval_activity_progress")
@XMLElement(name = "ActivityProgress")
public class FlowApprovalActivityProgress extends GeneratedElementable implements AccessInterface {

	public static final Field ACTIVITY_RELATION = ReflectionUtils.getField(FlowApprovalActivityProgress.class, "activity");
	public static final Field ACTIVITY_ROUND_RELATION = ReflectionUtils.getField(FlowApprovalActivityProgress.class, "activityRound");
	
	public static final Field FIELD_SIGNING_DATA = ReflectionUtils.getField(FlowApprovalActivityProgress.class, "signingData");
	public static final Field FIELD_SIGNATURE_DATA = ReflectionUtils.getField(FlowApprovalActivityProgress.class, "signatureData");

	@Key
	@DAOManaged(autoGenerated = true)
	@XMLElement
	private Integer activityProgressID;
	
	@DAOManaged(columnName = "activityRoundID")
	@ManyToOne
	@XMLElement
	private FlowApprovalActivityRound activityRound;

	@DAOManaged(columnName = "activityID")
	@ManyToOne
	@XMLElement
	private FlowApprovalActivity activity;

	@DAOManaged
	@XMLElement
	private Timestamp added;

	@DAOManaged
	@XMLElement
	private Timestamp completed;

	@DAOManaged
	@XMLElement
	private boolean denied;

	@DAOManaged(columnName = "completingUserID")
	@XMLElement(name = "CompletingUser")
	private User completingUser;

	@DAOManaged
	@OneToMany(autoGet = true, autoAdd = true, autoUpdate = true)
	@SimplifiedRelation(table = "flowapproval_activity_progress_resp_attr_users", remoteValueColumnName = "userID")
	@XMLElement(fixCase = true)
	private List<User> responsibleAttributedUsers;

	@DAOManaged
	@XMLElement
	private String comment;
	
	@DAOManaged
	@XMLElement
	private boolean automaticReminderSent;
	
	@DAOManaged
	private String signingData;
	
	@DAOManaged
	@XMLElement
	private Timestamp signedDate;

	@DAOManaged
	@XMLElement
	private String signedChecksum;

	@DAOManaged
	private String signatureData;

	public Integer getActivityProgressID() {
		return activityProgressID;
	}

	public void setActivityProgressID(Integer activityProgressID) {
		this.activityProgressID = activityProgressID;
	}

	public FlowApprovalActivity getActivity() {
		return activity;
	}

	public void setActivity(FlowApprovalActivity activity) {
		this.activity = activity;
	}

	public Timestamp getAdded() {
		return added;
	}

	public void setAdded(Timestamp added) {
		this.added = added;
	}

	public Timestamp getCompleted() {
		return completed;
	}

	public void setCompleted(Timestamp completed) {
		this.completed = completed;
	}

	public boolean isDenied() {
		return denied;
	}

	public void setDenied(boolean denied) {
		this.denied = denied;
	}

	public User getCompletingUser() {
		return completingUser;
	}

	public void setCompletingUser(User completer) {
		this.completingUser = completer;
	}

	public String getComment() {
		return comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public List<User> getResponsibleAttributedUsers() {
		return responsibleAttributedUsers;
	}

	public void setResponsibleAttributedUsers(List<User> responsibleAttributedUsers) {
		this.responsibleAttributedUsers = responsibleAttributedUsers;
	}

	public boolean isAutomaticReminderSent() {
		return automaticReminderSent;
	}

	public void setAutomaticReminderSent(boolean automaticReminderSent) {
		this.automaticReminderSent = automaticReminderSent;
	}

	public FlowApprovalActivityRound getActivityRound() {
		return activityRound;
	}

	public void setActivityRound(FlowApprovalActivityRound activityRound) {
		this.activityRound = activityRound;
	}

	public Timestamp getSignedDate() {
		return signedDate;
	}

	public void setSignedDate(Timestamp signedDate) {
		this.signedDate = signedDate;
	}

	public String getSignedChecksum() {
		return signedChecksum;
	}

	public void setSignedChecksum(String signedChecksum) {
		this.signedChecksum = signedChecksum;
	}

	public String getSigningData() {
		return signingData;
	}

	public void setSigningData(String signingData) {
		this.signingData = signingData;
	}

	public String getSignatureData() {
		return signatureData;
	}

	public void setSignatureData(String signatureData) {
		this.signatureData = signatureData;
	}

	@Override
	public String toString() {
		return getClass().getSimpleName() + " (activityProgressID=" + activityProgressID + ", activity=" + (activity == null ? null : activity.getActivityID()) + ", added=" + added + ", completed=" + completed + ", denied=" + denied + ", completingUser=" + completingUser + ")";
	}
	
	public boolean isMutable() {
		return completed == null && activityRound.getCompleted() == null && activityRound.getCancelled() == null;
	}

	@Override
	public boolean allowsAdminAccess() {
		return false;
	}

	@Override
	public boolean allowsUserAccess() {
		return false;
	}

	@Override
	public boolean allowsAnonymousAccess() {
		return false;
	}

	@Override
	public Collection<Integer> getAllowedGroupIDs() {
		return UserUtils.getGroupIDs(activity.getResponsibleGroups());
	}

	@Override
	public Collection<Integer> getAllowedUserIDs() {

		if (CollectionUtils.isEmpty(activity.getResponsibleUsers()) && responsibleAttributedUsers == null) {
			return null;
		}

		List<Integer> userIDs = new ArrayList<Integer>(CollectionUtils.getSize(activity.getResponsibleUsers()) + 1);

		if (activity.getResponsibleUsers() != null) {
			for (FlowApprovalActivityResponsibleUser responsibleUser : activity.getResponsibleUsers()) {

				if (!responsibleUser.isFallback() || (activity.getResponsibleUserAttributeNames() != null && responsibleAttributedUsers == null)) {
					userIDs.add(responsibleUser.getUser().getUserID());
				}
			}
		}

		if (responsibleAttributedUsers != null) {
			for (User user : responsibleAttributedUsers) {
				userIDs.add(user.getUserID());
			}
		}

		return userIDs;
	}
}
