package com.nordicpeak.flowengine.persondatasavinginformer.beans;

import java.io.Serializable;
import java.util.List;

import se.unlogic.standardutils.annotations.WebPopulate;
import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.ManyToMany;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.xml.GeneratedElementable;
import se.unlogic.standardutils.xml.XMLElement;

@Table(name = "person_data_informer_data_alternatives")
@XMLElement
public class InformerDataAlternative extends GeneratedElementable implements Serializable {

	private static final long serialVersionUID = -7896076910394000875L;

	@DAOManaged(autoGenerated = true)
	@Key
	@XMLElement
	private Integer alternativeID;

	@DAOManaged
	@WebPopulate(required = true, maxLength = 255)
	@XMLElement
	private String name;

	@DAOManaged
	@WebPopulate
	@XMLElement
	private boolean autoSelect;

	@DAOManaged
	@ManyToMany(linkTable = "person_data_informer_settings_data_alternatives")
	@XMLElement
	private List<FlowFamilyInformerSetting> flowFamilyInformerSettings;

	public Integer getAlternativeID() {

		return alternativeID;
	}

	public void setAlternativeID(Integer alternativeID) {

		this.alternativeID = alternativeID;
	}

	public String getName() {

		return name;
	}

	public void setName(String name) {

		this.name = name;
	}

	public boolean isAutoSelect() {

		return autoSelect;
	}

	public void setAutoSelect(boolean autoSelect) {

		this.autoSelect = autoSelect;
	}

	public List<FlowFamilyInformerSetting> getFlowFamilyInformerSettings() {

		return flowFamilyInformerSettings;
	}

	public void setFlowFamilyInformerSettings(List<FlowFamilyInformerSetting> flowFamilyInformerSettings) {

		this.flowFamilyInformerSettings = flowFamilyInformerSettings;
	}

	@Override
	public String toString() {

		return name + " (ID: " + alternativeID + ")";
	}
}