package com.nordicpeak.flowengine.persondatasavinginformer.beans;

import java.io.Serializable;
import java.util.List;

import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.ManyToMany;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.xml.GeneratedElementable;
import se.unlogic.standardutils.xml.XMLElement;

@Table(name = "person_data_informer_reason_alternatives")
@XMLElement
public class InformerReasonAlternative extends GeneratedElementable implements Serializable {
	
	private static final long serialVersionUID = 1046773173887815926L;

	@DAOManaged(autoGenerated = true)
	@Key
	@XMLElement
	private Integer alternativeID;
	
	@DAOManaged
	@XMLElement
	private String name;
	
	@DAOManaged
	@ManyToMany(linkTable="person_data_informer_settings_reason_alternatives")
	@XMLElement
	private List<FlowFamilyInformerSetting> flowFamilyInformerSettings;
	
	public Integer getAlternativeID() {
		return alternativeID;
	}
	
	public void setAlternativeID(Integer alternativeID) {
		this.alternativeID = alternativeID;
	}
	
	public String getName() {
		return name;
	}
	
	public void setName(String name) {
		this.name = name;
	}
	
	@Override
	public String toString(){
		return name;
	}
	
}
