package com.nordicpeak.teis.beans;

import java.sql.Timestamp;

import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.xml.GeneratedElementable;
import se.unlogic.standardutils.xml.XMLElement;

import com.nordicpeak.teis.enums.LogEventType;

@Table(name = "teis_integration_log")
public class IntegrationLog extends GeneratedElementable {

	@DAOManaged(autoGenerated = true)
	@Key
	@XMLElement
	private Integer logID;

	@XMLElement
	@DAOManaged
	private Integer flowID;

	@XMLElement
	@DAOManaged
	private Integer flowInstanceID;

	@XMLElement
	@DAOManaged
	private LogEventType eventType;

	@XMLElement
	@DAOManaged
	private Timestamp added;
	
	@XMLElement
	@DAOManaged
	private String message;

	public Integer getLogID() {

		return logID;
	}

	public void setLogID(Integer logID) {

		this.logID = logID;
	}

	public Integer getFlowID() {

		return flowID;
	}

	public void setFlowID(Integer flowID) {

		this.flowID = flowID;
	}

	public Integer getFlowInstanceID() {

		return flowInstanceID;
	}

	public void setFlowInstanceID(Integer flowInstanceID) {

		this.flowInstanceID = flowInstanceID;
	}

	public LogEventType getEventType() {

		return eventType;
	}

	public void setEventType(LogEventType eventType) {

		this.eventType = eventType;
	}

	public Timestamp getAdded() {

		return added;
	}

	public void setAdded(Timestamp added) {

		this.added = added;
	}
}
