package com.nordicpeak.teis.beans;

import java.sql.Timestamp;

import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.xml.GeneratedElementable;
import se.unlogic.standardutils.xml.XMLElement;

import com.nordicpeak.teis.enums.QueuedEventType;

@Table(name="teis_integration_queue")
@XMLElement
public class QueuedEvent extends GeneratedElementable {

	@DAOManaged(autoGenerated = true)
	@Key
	@XMLElement
	private Integer queueID;

	@XMLElement
	@DAOManaged
	private Integer flowID;

	@XMLElement
	@DAOManaged
	private Integer flowInstanceID;

	@XMLElement
	@DAOManaged
	private Integer eventID;

	@XMLElement
	@DAOManaged
	private QueuedEventType eventType;

	@XMLElement
	@DAOManaged
	private Timestamp queued;

	@XMLElement
	@DAOManaged
	private Timestamp lastSendAttempt;

	@XMLElement
	@DAOManaged
	private int sendAttempts;

	public Integer getQueueID() {

		return queueID;
	}

	public void setQueueID(Integer queueID) {

		this.queueID = queueID;
	}

	public Integer getFlowID() {

		return flowID;
	}

	public void setFlowID(Integer flowID) {

		this.flowID = flowID;
	}

	public Integer getFlowInstanceID() {

		return flowInstanceID;
	}

	public void setFlowInstanceID(Integer flowInstanceID) {

		this.flowInstanceID = flowInstanceID;
	}

	public Integer getEventID() {

		return eventID;
	}

	public void setEventID(Integer eventID) {

		this.eventID = eventID;
	}

	public QueuedEventType getEventType() {

		return eventType;
	}

	public void setEventType(QueuedEventType eventType) {

		this.eventType = eventType;
	}

	public Timestamp getQueued() {

		return queued;
	}

	public void setQueued(Timestamp queued) {

		this.queued = queued;
	}

	public Timestamp getLastSendAttempt() {

		return lastSendAttempt;
	}

	public void setLastSendAttempt(Timestamp lastSendAttempt) {

		this.lastSendAttempt = lastSendAttempt;
	}

	public int getSendAttempts() {

		return sendAttempts;
	}

	public void setSendAttempts(int sendAttempts) {

		this.sendAttempts = sendAttempts;
	}

}
