package com.nordicpeak.flowengine.flowapprovalmodule.beans;

import java.io.Serializable;
import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.List;

import se.unlogic.standardutils.annotations.WebPopulate;
import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.ManyToOne;
import se.unlogic.standardutils.dao.annotations.OrderBy;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.populators.StringPopulator;
import se.unlogic.standardutils.reflection.ReflectionUtils;
import se.unlogic.standardutils.validation.ValidationError;
import se.unlogic.standardutils.validation.ValidationException;
import se.unlogic.standardutils.xml.GeneratedElementable;
import se.unlogic.standardutils.xml.XMLElement;
import se.unlogic.standardutils.xml.XMLParser;
import se.unlogic.standardutils.xml.XMLParserPopulateable;
import se.unlogic.standardutils.xml.XMLValidationUtils;


@Table(name = "flowapproval_activitygroups_message_templates")
@XMLElement
public class FlowApprovalActivityGroupMessageTemplate extends GeneratedElementable implements Serializable, XMLParserPopulateable {

	public static final Field ACTIVITY_GROUP_RELATION = ReflectionUtils.getField(FlowApprovalActivityGroupMessageTemplate.class, "flowApprovalActivityGroup");

	private static final long serialVersionUID = 3268646669132872847L;

	@DAOManaged(autoGenerated = true)
	@Key
	@XMLElement
	private Integer templateID;

	@DAOManaged(columnName = "activityGroupID")
	@ManyToOne
	@XMLElement
	private FlowApprovalActivityGroup flowApprovalActivityGroup;

	@DAOManaged
	@OrderBy
	@WebPopulate(maxLength = 255, required = true, paramName = "messageTemplateName")
	@XMLElement
	private String name;

	@DAOManaged
	@WebPopulate(maxLength = 65535, required = true, paramName = "messageTemplateMessage")
	@XMLElement
	private String message;

	public Integer getTemplateID() {

		return templateID;
	}

	public void setTemplateID(Integer templateID) {

		this.templateID = templateID;
	}

	public FlowApprovalActivityGroup getFlowApprovalActivityGroup() {

		return flowApprovalActivityGroup;
	}

	public void setFlowApprovalActivityGroup(FlowApprovalActivityGroup flowApprovalActivityGroup) {

		this.flowApprovalActivityGroup = flowApprovalActivityGroup;
	}

	public String getName() {

		return name;
	}

	public void setName(String name) {

		this.name = name;
	}

	public String getMessage() {

		return message;
	}

	public void setMessage(String message) {

		this.message = message;
	}

	@Override
	public void populate(XMLParser xmlParser) throws ValidationException {

		List<ValidationError> errors = new ArrayList<>();

		name = XMLValidationUtils.validateParameter("name", xmlParser, true, 1, 255, StringPopulator.getPopulator(), errors);
		message = XMLValidationUtils.validateParameter("message", xmlParser, true, 1, 65535, StringPopulator.getPopulator(), errors);
		
		if (!errors.isEmpty()) {

			throw new ValidationException(errors);
		}
	}

	@Override
	public String toString() {

		return getClass().getSimpleName() + " (templateID=" + templateID + ", name=" + name + ")";
	}

}