package com.nordicpeak.flowengine.queries.generalmapquery.configuration;

import java.io.Serializable;
import java.lang.reflect.Field;
import java.util.List;

import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.ManyToOne;
import se.unlogic.standardutils.dao.annotations.OneToMany;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.reflection.ReflectionUtils;
import se.unlogic.standardutils.xml.GeneratedElementable;
import se.unlogic.standardutils.xml.XMLElement;

import com.nordicpeak.flowengine.queries.generalmapquery.GeneralMapQueryPrint;

@Table(name = "general_map_query_printconfiguration_prints")
@XMLElement
public class MapPrint extends GeneratedElementable implements Serializable {

	private static final long serialVersionUID = -1491185298804487479L;

	public static final Field PRINTCONFIGURATION_RELATION = ReflectionUtils.getField(MapPrint.class, "printConfiguration");
	public static final Field PRINTSERVICE_RELATION = ReflectionUtils.getField(MapPrint.class, "printService");
	public static final Field RESOLUTION_RELATION = ReflectionUtils.getField(MapPrint.class, "resolution");
	public static final Field SCALE_RELATION = ReflectionUtils.getField(MapPrint.class, "scale");
	public static final Field LAYOUT_RELATION = ReflectionUtils.getField(MapPrint.class, "layout");
	public static final Field OUTPUTFORMAT_RELATION = ReflectionUtils.getField(MapPrint.class, "outputFormat");

	@Key
	@DAOManaged(autoGenerated = true)
	@XMLElement
	private Integer mapPrintID;

	@DAOManaged
	@XMLElement
	private String name;

	@DAOManaged(columnName = "printConfigurationID")
	@ManyToOne
	@XMLElement
	private PrintConfiguration printConfiguration;

	@DAOManaged(columnName = "printServiceID")
	@ManyToOne
	@XMLElement
	private PrintService printService;

	@DAOManaged(columnName = "resolutionID")
	@ManyToOne
	@XMLElement
	private Resolution resolution;

	@DAOManaged(columnName = "scaleID")
	@ManyToOne
	@XMLElement
	private Scale scale;

	@DAOManaged(columnName = "layoutID")
	@ManyToOne
	@XMLElement
	private Layout layout;

	@DAOManaged(columnName = "outputFormatID")
	@ManyToOne
	@XMLElement
	private OutputFormat outputFormat;

	@DAOManaged
	@XMLElement
	private String alias;

	@DAOManaged
	@OneToMany
	@XMLElement
	private List<GeneralMapQueryPrint> mapQueryPrints;

	public Integer getMapPrintID() {

		return mapPrintID;
	}

	public void setMapPrintID(Integer mapPrintID) {

		this.mapPrintID = mapPrintID;
	}

	public String getName() {

		return name;
	}

	public void setName(String name) {

		this.name = name;
	}

	public PrintConfiguration getPrintConfiguration() {

		return printConfiguration;
	}

	public void setPrintConfiguration(PrintConfiguration printConfiguration) {

		this.printConfiguration = printConfiguration;
	}

	public PrintService getPrintService() {

		return printService;
	}

	public void setPrintService(PrintService printService) {

		this.printService = printService;
	}

	public Resolution getResolution() {

		return resolution;
	}

	public void setResolution(Resolution resolution) {

		this.resolution = resolution;
	}

	public Scale getScale() {

		return scale;
	}

	public void setScale(Scale scale) {

		this.scale = scale;
	}

	public Layout getLayout() {

		return layout;
	}

	public void setLayout(Layout layout) {

		this.layout = layout;
	}

	public OutputFormat getOutputFormat() {

		return outputFormat;
	}

	public void setOutputFormat(OutputFormat outputFormat) {

		this.outputFormat = outputFormat;
	}

	public String getAlias() {

		return alias;
	}

	public void setAlias(String alias) {

		this.alias = alias;
	}

	public List<GeneralMapQueryPrint> getMapQueryPrints() {

		return mapQueryPrints;
	}

	public void setMapQueryPrints(List<GeneralMapQueryPrint> mapQueryPrints) {

		this.mapQueryPrints = mapQueryPrints;
	}

}
