package com.nordicpeak.flowengine.queries.generalmapquery.configuration;

import java.io.Serializable;
import java.lang.reflect.Field;
import java.util.List;

import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.OneToMany;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.reflection.ReflectionUtils;
import se.unlogic.standardutils.xml.GeneratedElementable;
import se.unlogic.standardutils.xml.XMLElement;

@Table(name = "general_map_query_printservices")
@XMLElement
public class PrintService extends GeneratedElementable implements Serializable {

	private static final long serialVersionUID = 8380522116631287430L;
	
	public static final Field SCALES_RELATION = ReflectionUtils.getField(PrintService.class, "scales");
	public static final Field RESOLUTIONS_RELATION = ReflectionUtils.getField(PrintService.class, "resolutions");
	public static final Field LAYOUTS_RELATION = ReflectionUtils.getField(PrintService.class, "layouts");
	public static final Field OUTPUTFORMATS_RELATION = ReflectionUtils.getField(PrintService.class, "outputFormats");
	
	@Key
	@DAOManaged(autoGenerated = true)
	@XMLElement
	private Integer printServiceID;

	@DAOManaged
	@XMLElement
	private String name;

	@DAOManaged
	@XMLElement
	private String printServiceAddress;

	@DAOManaged
	@OneToMany
	@XMLElement
	private List<Scale> scales;

	@DAOManaged
	@OneToMany
	@XMLElement
	private List<Resolution> resolutions;

	@DAOManaged
	@OneToMany
	@XMLElement
	private List<Layout> layouts;

	@DAOManaged
	@OneToMany
	@XMLElement
	private List<OutputFormat> outputFormats;

	@DAOManaged
	@OneToMany
	@XMLElement
	private List<MapPrint> mapPrints;

	public Integer getPrintServiceID() {

		return printServiceID;
	}

	public void setPrintServiceID(Integer printServiceID) {

		this.printServiceID = printServiceID;
	}

	public String getName() {

		return name;
	}

	public void setName(String name) {

		this.name = name;
	}

	public String getPrintServiceAddress() {

		return printServiceAddress;
	}

	public void setPrintServiceAddress(String printServiceAddress) {

		this.printServiceAddress = printServiceAddress;
	}

	public List<Scale> getScales() {

		return scales;
	}

	public void setScales(List<Scale> scales) {

		this.scales = scales;
	}

	public List<Resolution> getResolutions() {

		return resolutions;
	}

	public void setResolutions(List<Resolution> resolutions) {

		this.resolutions = resolutions;
	}

	public List<Layout> getLayouts() {

		return layouts;
	}

	public void setLayouts(List<Layout> layouts) {

		this.layouts = layouts;
	}

	public List<OutputFormat> getOutputFormats() {

		return outputFormats;
	}

	public void setOutputFormats(List<OutputFormat> outputFormats) {

		this.outputFormats = outputFormats;
	}

	public List<MapPrint> getMapPrints() {

		return mapPrints;
	}

	public void setMapPrints(List<MapPrint> mapPrints) {

		this.mapPrints = mapPrints;
	}

}
