
package com.nordicpeak.flowengine.integration.callback.exceptions;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "StatusNotFoundFault", targetNamespace = "http://www.oeplatform.org/version/1.0/schemas/integration/callback")
public class StatusNotFoundException extends Exception
{

    private static final long serialVersionUID = 2017992736739679708L;
	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private StatusNotFound faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public StatusNotFoundException(String message, StatusNotFound faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public StatusNotFoundException(String message, StatusNotFound faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.nordicpeak.flowengine.integration.callback.StatusNotFound
     */
    public StatusNotFound getFaultInfo() {
        return faultInfo;
    }

}
