package com.nordicpeak.flowengine.notifications.beans;

import java.lang.reflect.Field;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;

import se.unlogic.hierarchy.core.handlers.SourceAttributeHandler;
import se.unlogic.hierarchy.core.interfaces.AttributeHandler;
import se.unlogic.hierarchy.core.interfaces.AttributeSource;
import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.OneToMany;
import se.unlogic.standardutils.dao.annotations.OrderBy;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.enums.Order;
import se.unlogic.standardutils.reflection.ReflectionUtils;
import se.unlogic.standardutils.xml.GeneratedElementable;
import se.unlogic.standardutils.xml.XMLElement;

import com.nordicpeak.flowengine.notifications.interfaces.Notification;

@Table(name = "flowengine_notifications")
@XMLElement(name = "Notification")
public class StoredNotification extends GeneratedElementable implements AttributeSource, Notification {
	
	
	public static final Field ATTRIBUTES_RELATION = ReflectionUtils.getField(StoredNotification.class, "attributes");
	
	private SourceAttributeHandler attributeHandler;
	
	@DAOManaged(autoGenerated = true)
	@Key
	@XMLElement
	private Integer notificationID;
	
	@DAOManaged
	@XMLElement
	private Integer sourceModuleID;
	
	@DAOManaged
	@XMLElement
	private Integer flowInstanceID;
	
	@DAOManaged
	@XMLElement
	private Integer userID;
	
	@DAOManaged
	@OrderBy(order = Order.DESC)
	@XMLElement
	private Timestamp added;
	
	@DAOManaged
	@XMLElement
	private Timestamp seen;
	
	@DAOManaged
	@XMLElement
	private String title;
	
	// Can be null
	@DAOManaged
	@XMLElement
	private String notificationType;
	
	// Can be null
	@DAOManaged
	@XMLElement
	private Integer externalNotificationID;
	
	// Can be null
	@DAOManaged
	@OneToMany(autoAdd = true, autoGet = true)
	@XMLElement
	private List<StoredNotificationAttribute> attributes;
	
	@XMLElement
	private NotificationExtra notificationExtra;
	
	@Override
	public Integer getNotificationID() {
		
		return notificationID;
	}
	
	public void setNotificationID(Integer notificationID) {
		
		this.notificationID = notificationID;
	}
	
	@Override
	public String getTitle() {
		return title;
	}
	
	public void setTitle(String title) {
		this.title = title;
	}
	
	@Override
	public Integer getSourceModuleID() {
		
		return sourceModuleID;
	}
	
	public void setSourceModuleID(Integer sourceModuleID) {
		
		this.sourceModuleID = sourceModuleID;
	}
	
	@Override
	public Integer getUserID() {
		
		return userID;
	}
	
	public void setUserID(Integer userID) {
		
		this.userID = userID;
	}
	
	@Override
	public Timestamp getAdded() {
		
		return added;
	}
	
	public void setAdded(Timestamp added) {
		
		this.added = added;
	}
	
	@Override
	public Timestamp getSeen() {
		
		return seen;
	}
	
	public void setSeen(Timestamp seen) {
		this.seen = seen;
	}
	
	@Override
	public String getNotificationType() {
		
		return notificationType;
	}
	
	public void setNotificationType(String notificationType) {
		
		this.notificationType = notificationType;
	}
	
	@Override
	public Integer getExternalNotificationID() {
		
		return externalNotificationID;
	}
	
	public void setExternalNotificationID(Integer externalNotificationID) {
		
		this.externalNotificationID = externalNotificationID;
	}
	
	@Override
	public List<StoredNotificationAttribute> getAttributes() {
		
		return attributes;
	}
	
	public void setAttributes(List<StoredNotificationAttribute> attributes) {
		
		this.attributes = attributes;
	}
	
	@Override
	public synchronized AttributeHandler getAttributeHandler() {
		
		if (attributeHandler == null) {
			
			this.attributeHandler = new SourceAttributeHandler(this, 255, 1024);
		}
		
		return attributeHandler;
	}
	
	@Override
	public void addAttribute(String name, String value) {
		
		if (this.attributes == null) {
			
			attributes = new ArrayList<StoredNotificationAttribute>();
		}
		
		attributes.add(new StoredNotificationAttribute(name, value));
	}
	
	public void setFlowInstanceID(Integer flowInstanceID) {
		this.flowInstanceID = flowInstanceID;
	}
	
	@Override
	public Integer getFlowInstanceID() {
		return flowInstanceID;
	}
	
	public NotificationExtra getNotificationExtra() {
		return notificationExtra;
	}
	
	public void setNotificationExtra(NotificationExtra notificationExtra) {
		this.notificationExtra = notificationExtra;
	}
	
	@Override
	public String toString() {
		return "sourceModuleID=" + sourceModuleID + ", flowInstanceID=" + flowInstanceID + ", userID=" + userID + ", title=" + title + ", notificationType=" + notificationType + ", externalNotificationID=" + externalNotificationID;
	}
	
}
