//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.08 at 11:18:26 AM CET 
//


package com.nordicpeak.teis.externalmessage;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.nordicpeak.teis.externalmessage package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Message_QNAME = new QName("http://www.oeplatform.org/version/1.0/schemas/integration/externalmessage", "Message");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.nordicpeak.teis.externalmessage
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ExternalMessage }
     * 
     */
    public ExternalMessage createExternalMessage() {
        return new ExternalMessage();
    }

    /**
     * Create an instance of {@link Attachment }
     * 
     */
    public Attachment createAttachment() {
        return new Attachment();
    }

    /**
     * Create an instance of {@link ExternalID }
     * 
     */
    public ExternalID createExternalID() {
        return new ExternalID();
    }

    /**
     * Create an instance of {@link Principal }
     * 
     */
    public Principal createPrincipal() {
        return new Principal();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExternalMessage }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.oeplatform.org/version/1.0/schemas/integration/externalmessage", name = "Message")
    public JAXBElement<ExternalMessage> createMessage(ExternalMessage value) {
        return new JAXBElement<ExternalMessage>(_Message_QNAME, ExternalMessage.class, null, value);
    }

}
