package com.nordicpeak.flowengine.beans;

import java.io.Serializable;
import java.util.List;

import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.ManyToOne;
import se.unlogic.standardutils.dao.annotations.OneToMany;
import se.unlogic.standardutils.dao.annotations.SimplifiedRelation;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.xml.GeneratedElementable;
import se.unlogic.standardutils.xml.XMLElement;

@Table(name = "flowengine_flow_family_automanager_rules")
@XMLElement
public class AutoManagerAssignmentRule extends GeneratedElementable implements Serializable {
	
	private static final long serialVersionUID = 2906850629442177083L;
	
	@DAOManaged(autoGenerated = true)
	@Key
	@XMLElement
	private Integer ruleID;
	
	@DAOManaged(columnName = "flowFamilyID")
	@ManyToOne
	private FlowFamily flowFamily;
	
	@DAOManaged
	@XMLElement
	private String attributeName;
	
	@DAOManaged
	@XMLElement
	private boolean invert;
	
	@DAOManaged
	@OneToMany(autoGet = true, autoAdd = true, autoUpdate = true)
	@SimplifiedRelation(table = "flowengine_flow_family_automanager_rule_values", remoteValueColumnName = "value")
	@XMLElement(fixCase = true)
	private List<String> values;
	
	@DAOManaged
	@OneToMany(autoGet = true, autoAdd = true, autoUpdate = true)
	@SimplifiedRelation(table = "flowengine_flow_family_automanager_rule_users", remoteValueColumnName = "userID")
	@XMLElement(fixCase = true)
	private List<Integer> userIDs;
	
	@DAOManaged
	@OneToMany(autoGet = true, autoAdd = true, autoUpdate = true)
	@SimplifiedRelation(table = "flowengine_flow_family_automanager_rule_groups", remoteValueColumnName = "groupID")
	@XMLElement(fixCase = true)
	private List<Integer> groupIDs;
	
	public Integer getRuleID() {
		return ruleID;
	}
	
	public void setRuleID(Integer ruleID) {
		this.ruleID = ruleID;
	}
	
	public boolean isInvert() {
		return invert;
	}
	
	public void setInvert(boolean invert) {
		this.invert = invert;
	}
	
	public FlowFamily getFlowFamily() {
		return flowFamily;
	}
	
	public void setFlowFamily(FlowFamily flowFamily) {
		this.flowFamily = flowFamily;
	}
	
	public List<Integer> getUserIDs() {
		return userIDs;
	}
	
	public void setUserIDs(List<Integer> userIDs) {
		this.userIDs = userIDs;
	}
	
	public List<Integer> getGroupIDs() {
		return groupIDs;
	}
	
	public void setGroupIDs(List<Integer> groupIDs) {
		this.groupIDs = groupIDs;
	}
	
	public String getAttributeName() {
		return attributeName;
	}
	
	public void setAttributeName(String attributeName) {
		this.attributeName = attributeName;
	}
	
	public List<String> getValues() {
		return values;
	}
	
	public void setValues(List<String> values) {
		this.values = values;
	}
	
}
