name: Run test
# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
  # At 01:00 every night (Please note: GitHub actions schedule is in UTC time).
    - cron: "0 1 * * *"
    
jobs:
  mirror:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04  # äldre Ubuntu med kompatibel Git/git-svn

    steps:
      # Installera Git, SVN och git-svn
      - name: Install dependencies
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y git subversion git-svn perl

      # Skapa katalog för SVN-kloning
      - name: Create mirror directory
        run: mkdir svn-mirror

      # Klona SVN-repo med standard layout
      - name: Clone SVN repository
        run: |
          git svn clone --stdlayout --no-metadata --prefix=svn/ svn://svn.nordicpeak.com/openeplatform svn-mirror

      - name: Add GitHub remote
        run: |
          cd svn-mirror
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
    
      # Push alla grenar och taggar till GitHub
      - name: Push to GitHub
        run: |
          cd svn-mirror
          git push --all origin
          git push --tags origin
          
  # Prevents this action from being disabled due to repository inactivity. See: https://docs.github.com/en/actions/administering-github-actions/usage-limits-billing-and-administration#disabling-and-enabling-workflows
  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
