name: Run test
# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
  # At 01:00 every night (Please note: GitHub actions schedule is in UTC time).
    - cron: "0 1 * * *"

jobs:
  mirror:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04  # kompatibel med git-svn

    steps:
      # Installera git, svn och git-svn
      - name: Install dependencies
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y git subversion git-svn perl

      # Initiera git-svn repo
      - name: Init git-svn repository
        run: |
          git svn init --stdlayout --prefix=svn/ svn://svn.nordicpeak.com/openeplatform svn-mirror

      # Hämta alla SVN-revisioner
      - name: Fetch SVN revisions
        run: |
          cd svn-mirror
          git svn fetch

      # Skapa main från trunk
      - name: Map trunk to main
        run: |
          cd svn-mirror
          git checkout -b main remotes/trunk

      # Lägg till GitHub som remote
      - name: Add GitHub remote
        run: |
          cd svn-mirror
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      # Push trunk som main
      - name: Push main branch
        run: |
          cd svn-mirror
          git push --set-upstream origin main

      # Push övriga SVN brancher
      - name: Push SVN branches
        run: |
          cd svn-mirror
          for branch in $(git for-each-ref --format='%(refname:short)' refs/remotes/svn/branches); do
            git checkout -b "${branch#svn/branches/}" "$branch"
            git push --set-upstream origin "${branch#svn/branches/}"
          done

      # Push SVN tags
      - name: Push SVN tags
        run: |
          cd svn-mirror
          git for-each-ref --format='%(refname:short)' refs/remotes/svn/tags | while read tag; do
            git tag "${tag#svn/tags/}" "$tag"
            git push origin "${tag#svn/tags/}"
          done
          
  # Prevents this action from being disabled due to repository inactivity. See: https://docs.github.com/en/actions/administering-github-actions/usage-limits-billing-and-administration#disabling-and-enabling-workflows
  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
