package com.nordicpeak.flowengine.beans;

import java.io.Serializable;
import java.lang.reflect.Field;

import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.ManyToOne;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.reflection.ReflectionUtils;
import se.unlogic.standardutils.xml.XMLElement;

@Table(name = "flowengine_flow_instance_query_search_values")
public class QuerySearchValue implements Serializable {

	private static final long serialVersionUID = 3506460953832755531L;

	public static final Field FLOW_INSTANCE_RELATION = ReflectionUtils.getField(QuerySearchValue.class, "flowInstance");

	@DAOManaged(autoGenerated = true)
	@Key
	@XMLElement
	private Integer querySearchValueID;

	@DAOManaged(columnName = "flowInstanceID")
	@ManyToOne
	protected FlowInstance flowInstance;

	@DAOManaged
	protected Integer queryID;

	@DAOManaged
	protected String searchValue;

	public QuerySearchValue() {}

	public QuerySearchValue(FlowInstance flowInstance, Integer queryID, String searchValue) {

		super();
		this.flowInstance = flowInstance;
		this.queryID = queryID;
		this.searchValue = searchValue;
	}

	public Integer getQuerySearchValueID() {

		return querySearchValueID;
	}

	public void setQuerySearchValueID(Integer querySearchValueID) {

		this.querySearchValueID = querySearchValueID;
	}

	public FlowInstance getFlowInstance() {

		return flowInstance;
	}

	public void setFlowInstance(FlowInstance flowInstance) {

		this.flowInstance = flowInstance;
	}

	public Integer getQueryID() {

		return queryID;
	}

	public void setQueryID(Integer queryID) {

		this.queryID = queryID;
	}

	public String getSearchValue() {

		return searchValue;
	}

	public void setSearchValue(String searchValue) {

		this.searchValue = searchValue;
	}

	@Override
	public String toString() {

		return "(flowInstance=" + flowInstance + ", queryID=" + queryID + ", searchValue=" + searchValue + ")";
	}

}
